export type Project = {
  slug: string;
  name: string;
  url: string;
  category: string;
  year: string;
  /** One-line summary for cards. */
  blurb: string;
  /** Longer intro for the case-study page. */
  summary: string;
  role: string[];
  stack: string[];
  highlights: string[];
  /** Screenshot in /public/work/{slug}.webp (generated by scripts/shots.mjs). */
  image: string;
};

export const projects: Project[] = [
  {
    slug: "maifa",
    name: "Maifa",
    url: "https://maifa.ke",
    category: "E-commerce",
    year: "2025",
    blurb: "Amaron car batteries with same-day delivery across Kenya.",
    summary:
      "A conversion-focused storefront for Maifa, Kenya's Amaron battery specialist. Built around a 'find my battery' flow, M-Pesa checkout, and same-day delivery promises that turn anxious, time-pressed buyers into confident customers.",
    role: ["Design", "Front-end", "E-commerce"],
    stack: ["Web", "Storefront", "M-Pesa"],
    highlights: [
      "Vehicle-based battery finder",
      "Same-day delivery & installation messaging",
      "Trust strip: warranty, M-Pesa, trade-in",
    ],
    image: "/work/maifa.jpg",
  },
  {
    slug: "porridge-powder",
    name: "Porridge Powder",
    url: "https://porridgepowder.com",
    category: "E-commerce · Brand",
    year: "2025",
    blurb: "JIDAN instant nutritious porridge, sold direct to consumers.",
    summary:
      "A warm, appetite-led brand store for JIDAN instant porridge. Soft, organic visuals carry a health-first message while a streamlined shop and countrywide-delivery banner keep the path to purchase short.",
    role: ["Brand", "Design", "Front-end"],
    stack: ["Web", "Storefront"],
    highlights: [
      "Appetite-driven brand system",
      "Health-benefits storytelling",
      "Direct-to-consumer checkout",
    ],
    image: "/work/porridge-powder.jpg",
  },
  {
    slug: "glory-care",
    name: "Glory Care Services",
    url: "https://glorycareservices.com",
    category: "Service · Healthcare",
    year: "2025",
    blurb: "NDIS-registered disability care provider in Alice Springs.",
    summary:
      "A reassuring, human site for an NDIS-registered care provider. Photography-led design and a clear 'get started' journey help participants and families understand services and reach out with confidence.",
    role: ["Design", "Front-end", "Content"],
    stack: ["Web", "Lead-gen"],
    highlights: [
      "NDIS-aligned information architecture",
      "Warm, trust-building visuals",
      "Frictionless enquiry flow",
    ],
    image: "/work/glory-care.jpg",
  },
  {
    slug: "pay-after-delivery",
    name: "Pay After Delivery",
    url: "https://payafterdelivery.co.ke",
    category: "E-commerce",
    year: "2025",
    blurb: "Kids' ride-on toys & quad bikes with pay-on-delivery.",
    summary:
      "A playful toy store built on a single powerful promise: pay after delivery. Bright, energetic merchandising and a friendly shopping flow lower the risk for parents buying online for the first time.",
    role: ["Design", "Front-end", "E-commerce"],
    stack: ["Web", "Storefront"],
    highlights: [
      "Pay-on-delivery trust model",
      "Category-led merchandising",
      "WhatsApp-first support",
    ],
    image: "/work/pay-after-delivery.jpg",
  },
  {
    slug: "flex-interiors",
    name: "Flex Interiors",
    url: "https://flexinteriors.co.ke",
    category: "Brand · Portfolio",
    year: "2024",
    blurb: "Premium interior design studio in Nairobi.",
    summary:
      "An editorial, dark-mode portfolio for a premium Nairobi interior studio. Confident serif typography and a refined blue palette frame the work and drive high-intent 'free consultation' enquiries.",
    role: ["Brand", "Design", "Front-end"],
    stack: ["Web", "Portfolio"],
    highlights: [
      "Editorial dark-mode system",
      "Project-led portfolio",
      "Consultation conversion flow",
    ],
    image: "/work/flex-interiors.jpg",
  },
  {
    slug: "blue-lilac-tours",
    name: "Blue Lilac Tours",
    url: "https://bluelilactours.com",
    category: "Travel · Booking",
    year: "2025",
    blurb: "East Africa safari & travel booking experiences.",
    summary:
      "An immersive travel site for an East Africa tour operator. A full-bleed video hero and curated trips invite visitors into the Great Migration, while multi-currency pricing and clear CTAs support international booking.",
    role: ["Design", "Front-end", "Booking"],
    stack: ["Web", "Booking"],
    highlights: [
      "Cinematic video hero",
      "Curated trips & itineraries",
      "Multi-currency, global-ready",
    ],
    image: "/work/blue-lilac-tours.jpg",
  },
];

export const getProject = (slug: string) =>
  projects.find((p) => p.slug === slug);
